name: Deploy API
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t emcpheron/aws-test .

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Login to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS }}

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: test
          environment_name: Test-env
          existing_bucket_name: elasticbeanstalk-us-east-1-707282035250
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
