name: Deploy API
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t emcpheron/aws-test .

      - name: Login to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS }}
          
      - name: Generate deployment package
        run: zip -r build.zip . -x '*.git*'

      - name: Upload ZIP to S3
        run: |
          aws s3 cp build.zip s3://turndown-cicd-test-bucket/builds/build.zip
          echo "S3_BUCKET=turndown-cicd-test-bucket" >> $GITHUB_ENV
          echo "S3_KEY=builds/build.zip" >> $GITHUB_ENV
