name: Deploy API
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS }}

      - name: Upload to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}
          docker build -t turndown/api .
          docker tag turndown/api:latest ${{ secrets.AWS_ECR_URL }}/turndown/api:latest
          docker push ${{ secrets.AWS_ECR_URL }}/turndown/api:latest
